spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/db/missionTest
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create